### ISSUE TITLE
exit関数

### ISSUE THREAD

**Issue by RIshimoto** [kayo289/minishell#11]
exit.cを作る。

**Comment by RIshimoto** [comment]
exit関数はEOFを送る。

**Comment by RIshimoto** [comment]
終了コードについて
http://itdoc.hitachi.co.jp/manuals/3020/30203S3530/JPAS0289.HTM

**Comment by RIshimoto** [comment]
exit関数内で$?に値をいれていださい。

**Comment by RIshimoto** [comment]
こんな感じ
```
void minish_exit(int status)
{
   $?(後でいい感じの変数名を付ける) = status;
   exit(status);
}
int main(int argc, char **argv)
{
   minish_exit(0);
}
```
minishell.hにvoid minish_exit(int status)を書いて、ほかのファイルからも関数を使えるようにする。
他ファイルのexitはすべてminish_exitに置き換える。（$?に値を代入するため）

**Comment by RIshimoto** [comment]
#46 からやってね♡

**Comment by RIshimoto** [comment]
exitの引数は数字。終了ステータスを指定するもの。

**Comment by RIshimoto** [comment]
![image](https://user-images.githubusercontent.com/57135683/110096787-a720f280-7de1-11eb-8a5a-b2a3a545d675.png)
参考文献：http://web.wakayama-u.ac.jp/~tokoi/lecture/shori1/2002/04.html

**Comment by kayo289** [comment]
exit [n]
ステータス n でシェルを終了させます。 n を省略すると、 終了ステータスは最後に実行したコマンドの終了ステータスとなります。 シェルが終了する前には、 EXIT に対するトラップが実行されます。
https://linuxjm.osdn.jp/html/GNU_bash/man1/bash.1.html
