### ISSUE TITLE
組み込みコマンドの共有ライブラリを作る

### ISSUE THREAD

**Issue by kayo289** [kayo289/minishell#121]
ここでmainを消す

**Comment by RIshimoto** [comment]
mainを消すというより、mainからcdに名前を変える

**Comment by RIshimoto** [comment]
https://sleepy-yoshi.hatenablog.com/entry/20090510/p1

**Comment by RIshimoto** [comment]
静的ライブラリを動的ライブラリに
http://ttanimu.blogspot.com/2013/07/blog-post_10.html

https://www.it-swarm.jp.net/ja/c/%E9%9D%99%E7%9A%84%E3%83%A9%E3%82%A4%E3%83%96%E3%83%A9%E3%83%AA%E3%82%92%E5%85%B1%E6%9C%89%E3%83%A9%E3%82%A4%E3%83%96%E3%83%A9%E3%83%AA%E3%81%AB%E5%A4%89%E6%8F%9B%E3%81%97%E3%81%BE%E3%81%99%E3%81%8B%EF%BC%9F/957882995/
