### ISSUE TITLE
パイプ

### ISSUE THREAD

**Issue by kayo289** [kayo289/minishell#13]
- [ ] パイプを実装する

**Comment by RIshimoto** [comment]
パイプ実装
再帰（注意）これは違うってことになりました（2/26）
- https://www.haya-programming.com/entry/2018/11/08/185349

配列
- https://keiorogiken.wordpress.com/2017/12/15/%E3%82%B7%E3%82%A7%E3%83%AB%E3%81%AE%E5%A4%9A%E6%AE%B5%E3%83%91%E3%82%A4%E3%83%97%E3%82%92%E8%87%AA%E4%BD%9C%E3%81%97%E3%81%A6%E3%81%BF%E3%82%8B/

**Comment by RIshimoto** [comment]
パイプとリダイレクトの違いはリダイレクトのissueに書いてあります。

**Comment by RIshimoto** [comment]
environを使おう！
execvpの第三引数は環境変数。
http://c-lang.net/execve/index.html

**Comment by RIshimoto** [comment]
pipeのイメージが克明に
![](https://media.geeksforgeeks.org/wp-content/uploads/sharing-pipe.jpg)

**Comment by RIshimoto** [comment]
pipe関数について
- https://www.ne.jp/asahi/hishidama/home/tech/c/pipe.html

**Comment by RIshimoto** [comment]
rnittaくんより、パイプで生成されるプロセスは親子の関係ではなくて、兄弟。
<img width="428" alt="bash" src="https://user-images.githubusercontent.com/57135683/109254673-db227380-7835-11eb-871c-ee223495efcb.png">
![-28-638](https://user-images.githubusercontent.com/57135683/109254797-11f88980-7836-11eb-8b1b-d8260b0ac832.jpg)

**Comment by RIshimoto** [comment]
wait が実行されなかった場合には、終了した子プロセスは 「ゾンビ」状態で残り続ける 

waitのmanより

**Comment by RIshimoto** [comment]
dup2の使い方
http://www.kis-lab.com/serikashiki/C/C04.html

**Comment by RIshimoto** [comment]
Unix Pipes
http://web.cse.ohio-state.edu/~mamrak.1/CIS762/pipes_lab_notes.html

**Comment by RIshimoto** [comment]
|&も作らなきゃいけないかも

**Comment by RIshimoto** [comment]
![image](https://user-images.githubusercontent.com/57135683/111419890-951e4880-872d-11eb-9990-fbe934de2f73.png)
これエラー出る順番、grepからなんだ、、、

**Comment by RIshimoto** [comment]
パイプラインの一部として起動された組み込みコマンドは、 サブシェル環境で実行されます。サブシェル環境に対して行われた変更は、 元のシェル実行環境に影響を及ぼすことはできません。
