### ISSUE TITLE
リダイレクト

### ISSUE THREAD

**Issue by kayo289** [kayo289/minishell#14]
- [ ] リダイレクトを作る
リダイレクトっていうのはそもそも、標準出力の接続先を画面からファイルに変更するようにシェルに対して指示すること。

**Comment by RIshimoto** [comment]
- [ ] 「>>」
- [ ] 「<」
- [ ] 「>」

**Comment by RIshimoto** [comment]
リダイレクトも結局はパイプ機能。
以下の記事を活用すればいけるかも、、、？あくまで仮説。
https://qiita.com/edo_m18/items/989d2907d4627e19ff65

**Comment by RIshimoto** [comment]
「>」と「>>」のちがい
どちらもファイル出力で使う。
「>」はファイルに上書き。
「>>」はファイル追記
参考文献
https://jj-blues.com/cms/column-differencekagikakko/

**Comment by RIshimoto** [comment]
標準出力をリダイレクトさせる1>と標準エラー出力をリダイレクトさせる2>にも対応させる。

**Comment by RIshimoto** [comment]
パイプとリダイレクトの違い
リダイレクトは、標準出力(標準エラー出力)をファイルに置き換える機能
- ファイル --> 標準入力
- 標準出力 --> ファイル
- 標準エラー出力 --> ファイル
パイプはこれを
- 標準出力 --> 標準入力
とファイルを介さずやってるだけ！
要するにfdを変えるだけ
https://www.kcube.co.jp/wakaba/server/redirect_and_pipe.html

**Comment by RIshimoto** [comment]
これやん！！！
http://hensa40.cutegirl.jp/archives/1438

**Comment by RIshimoto** [comment]
上書きはopenでいったんサイズ０にしたうえで、writeするのかな？
->そうでした。open("<file名>", O_CREAT | O_RDWR | O_TRUNC, S_IREAD | S_IWRITE)でおけ
追記はopen("<file名>", O_CREAT | O_RDWR | O_APPEND, S_IREAD | S_IWRITE)
http://cgengo.sakura.ne.jp/open.html

**Comment by RIshimoto** [comment]
cd < (path)
こういうことができる。実装どうすんねーん。
無理ぽ。。。

**Comment by RIshimoto** [comment]
(file) > catはダメ
cat < (file)はok
<は標準入力をファイルにリダイレクトする
">"は標準出力をファイルにリダイレクトする

**Comment by RIshimoto** [comment]
各コマンドでやる形になるかも。かよお願い。

**Comment by RIshimoto** [comment]
![image](https://user-images.githubusercontent.com/57135683/110948314-8974ff80-8384-11eb-941b-06841fa4c254.png)
すげーむずいよな
