### ISSUE TITLE
「$?」

### ISSUE THREAD

**Issue by kayo289** [kayo289/minishell#16]
- [ ]  ![image](https://user-images.githubusercontent.com/57135683/115433390-7a665480-a242-11eb-81ae-b17f52269eec.png)

- [ ]  ![image](https://user-images.githubusercontent.com/57135683/115433493-99fd7d00-a242-11eb-80ab-4c1501c3c9e3.png)

- [ ]  ![image](https://user-images.githubusercontent.com/57135683/115433544-aaadf300-a242-11eb-9441-738e8b9c8502.png)

- [ ]  ![image](https://user-images.githubusercontent.com/57135683/115433636-bdc0c300-a242-11eb-8f19-b18990a99bd5.png)

- [ ] ![image](https://user-images.githubusercontent.com/57135683/115433960-13956b00-a243-11eb-8f66-52916ac96b09.png)

- [ ] ![image](https://user-images.githubusercontent.com/57135683/115434162-59eaca00-a243-11eb-87df-b8439786f22c.png)

**Comment by RIshimoto** [comment]
直前に実行されたコマンドの終了ステータスが設定される。
参考文献
https://shellscript.sunone.me/variable.html#%E7%89%B9%E6%AE%8A%E5%A4%89%E6%95%B0%E3%81%A8%E3%81%AF
https://shellscript.sunone.me/exit_status.html#%E7%B5%82%E4%BA%86%E3%82%B9%E3%83%86%E3%83%BC%E3%82%BF%E3%82%B9%E3%81%A8%E3%81%AF

**Comment by RIshimoto** [comment]
割と最後あたりでも実装してもいいかも

**Comment by RIshimoto** [comment]
何もないときにCtrl+Cを押すと、1になる。

**Comment by RIshimoto** [comment]
yufukuyaさんより、
レビュー時にtotaiseiさんに見つけていただいた我々のminishellと違った本家の挙動を共有します
普通のcommand not found（/bin/asdf/asdf）は 127だけど /bin/ls/asdf ; echo $? みたいに途中に存在するファイルがあると126になる
何もないときに control-c を押すと echo $? が1に変わってる

**Comment by kayo289** [comment]
終了ステータスはシェル変数に保存されているらしい。
PIPESTATUS
フォアグラウンドで最後に実行したパイプラインの各プロセスの 終了ステータスのリストを含む配列変数です (後述の 配列 を参照)。 パイプラインには 1 つのコマンドしかなくてもかまいません。
https://linuxjm.osdn.jp/html/GNU_bash/man1/bash.1.html
