### ISSUE TITLE
キーバインドについて

### ISSUE THREAD

**Issue by RIshimoto** [kayo289/minishell#164]
おそらくこのissueではキーバインドを取り扱います。
![image](https://user-images.githubusercontent.com/57135683/112437083-e6f84b80-8d89-11eb-931a-35b32fcfc395.png)
-p
readline の関数の名前と割り当てを表示します。 表示は、再び読み込みできる形式で出力されます。
まだまだ下にもあるよ

これらキーバインドに対応

**Comment by kayo289** [comment]
これって、現在のpdfでも対応させる必要がある？
