### ISSUE TITLE
echo実装

### ISSUE THREAD

**Issue by RIshimoto** [kayo289/minishell#26]
- [x] -nオプション
-nオプションは改行なし

**Comment by RIshimoto** [comment]
echoの基本動作
- [ ] 文字列の出力
echoのあとの文字列を出力する。""があってもなくても
```
>echo Hello!
Hello!

>echo "Hello!"
Hello!
```

おぉん？なケース
```
$echo """
quote>

$echo "he" "llo"
he llo

$echo "he""llo"
hello

$echo "he"a"llo"
heallo

$echo "h"e" "
he

$echo "h"e" " "
quote>
```
- [ ] 変数の表示
```
>a=1200
>echo $a
1200
```
$aでも${a}でも変数を出力できるように。
ただ、{}とつけなかった場合、$以降の空白までの文字が一つの変数としてみなされる。
```
>a=1200
>echo c$at
c
>echo c${a}t
c1200t
```
登録されてない変数はなにも出力されない
```
>echo $gyoza

```
- [ ] 変数と文字列を同時に表示する
```
>a=1200
>echo weigth $a g
weight 1200 g
```
- [ ] 変数を複数表示する
```
>menu=coffee
>price=500
>echo order:$menu price:$price Yen
order:coffee price:500 Yen
```
- [ ] 計算値を表示する
```
>n=5
>echo Menu:$menu Number:$n price:`expr $price \* $n` Yen
Menu:coffee Number:5 price:2500 Yen
```
掛け算は\*に注意されたし（*がワイルドカードになっちゃうから）
これを基にテストを作ってください。

**Comment by RIshimoto** [comment]
- [ ] issueにもあるがダブルクォーテーションが途切れていたら入力待ち
＜懸念点>
```
echo "Hello\n
quote>World"
```
としたときgnlで処理すると、
echo "Hello\0
と
World\0"
という二行になる。
これを
echo "Hello\nWorld"として扱いたい。

これはコマンド入力のときに何とかする。echoでは気にすんな

**Comment by RIshimoto** [comment]
gnlを使うことでさらに問題があーる。
gnlは改行を\0にしてしまうので、
echo "Hello\nWorld"とecho "Hello\0World"の区別がつかなくなーる。

**Comment by RIshimoto** [comment]
「`」と「"」と「'」の違い
- [ ] シングルクォーテーション「'」の場合
```
>DIR=pwd
>echo '$DIR'
$DIR
```
- [ ] ダブルクォーテーション「"」の場合
```
>echo "$DIR"
pwd
```
- [ ] バッククォーテーション「`」の場合
引用符内をコマンドとしてみなして実行結果と置き換える。変数も展開される。
```
>echo `$DIR`
/home/vagrant
```
```
>gyoza=ls
>echo `$gyoza`
(lsコマンドの結果が出力される)

>g=l
>echo `${g}s`
(lsコマンドの結果が出力される)
```
ないコマンドは何も出力されない
```
>echo `$aaa`

```
参考文献
https://eng-entrance.com/linux-command-echo#i-8

**Comment by RIshimoto** [comment]
- [ ] エスケープ文字を考える。
\をつけたらふつうの文字として使えるように
```
$echo \a
a

$echo "\a"
\a

$echo "\""
"

$echo \"
"

$echo \
quote>
```

**Comment by RIshimoto** [comment]
#43 からやってね♡

**Comment by kayo289** [comment]
- [ ] 「echo \」も考慮する

![image](https://user-images.githubusercontent.com/39555606/108716794-e6d51800-755f-11eb-8744-0d1e9f34b114.png)

- [ ] 変数展開
