### ISSUE TITLE
各種テストツールを検証

### ISSUE THREAD

**Issue by kayo289** [kayo289/minishell#283]
[Minishell-tester](https://github.com/solaldunckel/minishell-tester) - solaldunckel
[List of commands to Test](https://docs.google.com/spreadsheets/d/1BLU6C9S7aoCl01x74GiW7s4xpEWWJ1cPrMTcLwISruk/edit#gid=1627853444) - bbrunet && julnolle
[List of commands to Test](https://docs.google.com/spreadsheets/d/1fniV2dSRB5TaFGyX3O-iK0u61xR5jDdkFKYonKpilIc/edit#gid=0) - mashar && vparekh
[List of commands to Test](https://github.com/t0mm4rx/minishell_tests) - t0mm4rx
[Minishell-tester](https://github.com/thallard/minishell_tester) - thallard
[42TESTERS-MINISHELL](https://github.com/Mazoise/42TESTERS-MINISHELL) - Mazoise
[minishell_test](https://github.com/cacharle/minishell_test) - cacharle
[minishell](https://pypi.org/project/minishell-test/0.0.5/) - 誰が作ったか分からない

* https://github.com/nafuka11/42_minishell_tester 
  * 一番最新
  
どのテスターも正常に動かない。

**Comment by kayo289** [comment]
これは動いた
https://github.com/cacharle/minishell_test

**Comment by RIshimoto** [comment]
ふかださんを信じろ
