### ISSUE TITLE
仕様変更への対応

### ISSUE THREAD

**Issue by kayo289** [kayo289/minishell#303]

**Comment by kayo289** [comment]
1. 事例1
ターミナルの入力れいは以下の通り
![image](https://user-images.githubusercontent.com/39555606/133785882-091bccce-8bdb-46f4-b1f7-e42ab522d6d5.png)
実際: \$
pdfの仕様: \$\
2. 事例2
~~ターミナル: echo | |~~
ターミナル: echo 半角スペース | 半角スペース |
実際: syntax errorに引っかかる
pdfの仕様: |半角スペース|

**Comment by RIshimoto** [comment]
> ターミナル: echo "$"
実際: $
pdfの仕様: $\

$\という出力はどうして？


>ターミナル: echo | |
実際: syntax errorに引っかかる
pdfの仕様: | |

手元で動かしてみましたが、syntaxerrorは出ませんでした。
