### ISSUE TITLE
静的コード解析

### ISSUE THREAD

**Issue by RIshimoto** [kayo289/minishell#39]
Norm対応のこと

**Comment by RIshimoto** [comment]
グローバル変数として使いたい場合は変数名がenvironのままだとnormに通りません。
#define _GNU_SOURCE
#include <unistd.h>

ubuntuでしか試してないのですが、こうするとunistd.hヘッダーの中でenvironが定義されるので、
environグローバル変数をそのまま使えて、normに通るはずです。

※macだと使えないらしいです。mainの第三引数を使う方が安全。。？

**Comment by RIshimoto** [comment]
normのアップデートをわするるな

**Comment by kayo289** [comment]
- [x] includes/
- [x] src/bltin
- [x] src/error
- [x] src/free
- [x] src/intepreter
- [x] src/laxer
- [x] src/libft
- [x] src/parser
- [x] src/prompt
- [x] src/queue
- [x] src/shell_variable
- [x] src/util
- [x] src/minishell
