### ISSUE TITLE
cd関数

### ISSUE THREAD

**Issue by RIshimoto** [kayo289/minishell#6]
cdコマンドに対応した関数を作る。
chdirを使う。
<参考プログラム>
http://cgengo.sakura.ne.jp/chdir.html

**Comment by RIshimoto** [comment]
cdの基本動作

- [ ] 現在のユーザーのホームディレクトリへの移動
```
$cd
$cd ~
```
- [ ] 相対パスでの移動
```
$cd home
$cd ./home
```

- [ ] 絶対パスへの移動
```
$cd /home
$cd /
```

**Comment by RIshimoto** [comment]
cd < ..
こういうことできるらしい

**Comment by RIshimoto** [comment]
#41 からやってね♡

**Comment by RIshimoto** [comment]
cd時にOLDPWDとPWDが書き変わっているか

**Comment by RIshimoto** [comment]
cdで移動する先はHOMEという環境変数で保存されている先。

https://qiita.com/Kotabrog/items/144e6e314ce82fb3f683

**Comment by RIshimoto** [comment]
cdの実装
https://ie.u-ryukyu.ac.jp/~e045713/shell/actX.html#program

**Comment by RIshimoto** [comment]
cd [-L|[-P [-e]]] [dir]
カレントディレクトリを dir に変更します。 変数 HOME の値が dir のデフォルト値です。変数 CDPATH は、 dir を含むディレクトリの検索パスを定義します。 CDPATH 内では候補ディレクトリ名はコロン (:) で区切ります。 CDPATH 中に空のディレクトリ名がある場合、これはカレントディレクトリ (つまり ``.'') を意味します。 dir がスラッシュ (/) で始まる場合には、 CDPATH は使われません。  

~~-P オプションは、シンボリックリンクを辿らないで物理的なディレクトリ構造を 使うように指示します (組み込みコマンド set の -P オプションも参照)。 -L オプションを指定すると、シンボリックリンクを辿るようになります。 -e オプションを -P オプションと同時に指定すると、ディレクトリの変更が成功した後に カレントディレクトリが判定できない場合、cd は失敗のステータスを返します。 引き数に - を指定するのは、 $OLDPWD を指定するのと同じ意味です。 CDPATH 内の空以外のディレクトリ名が使われたときや、 - が最初の引き数のときに、ディレクトリの変更が成功すると、 新しいディレクトリの絶対パス名が標準出力に書かれます。 ディレクトリの変更が成功した場合には返り値は真になり、 そうでない場合には偽になります。~~(今の所オプションの実装予定は無いので打ち消し線を入れています)

**Comment by RIshimoto** [comment]
あれ、うまくcd作ったはずなのにディレクトリ移動しないよってときに見る記事
https://satoru-takeuchi.hatenablog.com/entry/2020/03/26/010711

**Comment by kayo289** [comment]
NULLポインタを渡した場合、 getcwdの中で PATH_MAX分のメモリを動的に確保(malloc)します。その代わり、プログラマが getpwdによって確保されたメモリを明示的にfree(解放)する必要があります。
https://kaworu.jpn.org/kaworu/2007-10-01-1.php
