### ISSUE TITLE
環境変数

### ISSUE THREAD

**Issue by RIshimoto** [kayo289/minishell#65]

**Comment by RIshimoto** [comment]
https://qiita.com/angel_p_57/items/480e3fd4552e52199835

環境変数とは、"プログラムの挙動を調整するためのパラメータの一種であって、プロセス毎に保持・管理するもの"....うんちーーーー！
けどこの記事すごくいい。ちぇけら！

**Comment by RIshimoto** [comment]
シェルに依存しない環境変数などはは~/.proflieに書くんだって！
https://ac-as.net/linux-environment-variable/#

**Comment by RIshimoto** [comment]
ksuzukiより「シェル変数と環境変数の違い」
https://qiita.com/Kotabrog/items/144e6e314ce82fb3f683

**Comment by RIshimoto** [comment]
そもそも環境変数は設定するものではなくて、親プロセスから引き継ぐもの。
envpやenvironをコマンドライン引数で受け取って環境変数を使えばよろしいのではないか？
「envp - main関数３つ目の引数」
https://bussorenre.hatenablog.jp/entry/2014/07/02/103959
貼っときます、読んどけぇ

**Comment by RIshimoto** [comment]
プログラムの起動時には、 環境 (environment) と呼ばれる文字列の配列が渡されます。 これは 変数名-値 のペアからなるリストで、 変数名=値 という形になります。
シェルは、環境を操作する様々な方法を提供しています。 起動時には、シェルは自分自身の環境を調べ、 見つかった名前それぞれに対してパラメータを生成し、 それに自動的に子プロセスへの エクスポート (export) の印を付けます。実行されたコマンドは環境を継承します。 export コマンドまたは declare -x コマンドを用いると、 パラメータや関数の追加と削除を環境に対して行えます。 環境内のパラメータの値が変更されると、 新しい値は環境の一部となり、古い値と置き換わります。 実行されたコマンドが継承する環境は、 シェルの最初の環境から、 変数の値がシェル中で変更されたり、 一部のペアが unset コマンドで削除されたり、 export コマンドや declare -x コマンドで追加されたりしたものになります。

単純なコマンド や関数に対する環境は、一時的に修正できます。 これは、既に パラメータ の項で説明したように、パラメータ代入を前に置くことで行います。 このような代入が影響を与えるのは、 そのコマンドが参照する環境だけです。

-k オプションを設定 (後述の組み込みコマンド set を参照) すると、コマンド名の前に置いたものだけではなく、 全ての パラメータ代入がそのコマンドの環境に影響を与えます。

bash が外部コマンドを起動したときには、変数 _ にはコマンドの完全なファイル名が設定され、 環境変数としてそのコマンドに渡されます。  

参考文献：https://linuxjm.osdn.jp/html/GNU_bash/man1/bash.1.html

**Comment by kayo289** [comment]
環境変数の仕様として、親プロセスから子プロセスに複製され、子プロセスでの変更は親プロセスに影響しないらしい。親プロセスの環境変数に、子プロセスからアクセスできないようにしておく必要がありそう？
https://github.com/y-uchiida/clang-training/blob/main/environment-variables_in_c/commentary.md

**Comment by RIshimoto** [comment]
> 環境変数の仕様として、親プロセスから子プロセスに複製され、子プロセスでの変更は親プロセスに影響しないらしい。親プロセスの環境変数に、子プロセスからアクセスできないようにしておく必要がありそう？
> https://github.com/y-uchiida/clang-training/blob/main/environment-variables_in_c/commentary.md

@kayo289 
実装してみてから私たちのプログラムがどうなっているか見てみよう

**Comment by RIshimoto** [comment]
この記事をよんでシェル変数と環境変数の理解が深まった気がします。
シェル変数の中でexportされたものがエクスポート変数、されてないものがローカル変数と呼ばれます。
このエクスポート変数がいわゆる環境変数と呼ばれるならば、環境変数はシェル変数の一種ということになります。
https://flex.phys.tohoku.ac.jp/texi/sh/node24.html

**Comment by RIshimoto** [comment]
一応載せておきます
「エクスポート変数」
https://flex.phys.tohoku.ac.jp/texi/sh/node24.html
