### ISSUE TITLE
pwd関数

### ISSUE THREAD

**Issue by RIshimoto** [kayo289/minishell#7]
pwd.cを作る。
getcwdを使う。
<サンプルプログラム>
http://cgengo.sakura.ne.jp/getcwd.html

**Comment by RIshimoto** [comment]
#42  からやってね♡

**Comment by kayo289** [comment]
![image](https://user-images.githubusercontent.com/39555606/108714662-2e0dd980-755d-11eb-93bd-08020259677d.png)

- [ ] pwdの後に何がきてもエラーにならない。
